"""ADMET property endpoints — drug-likeness predictions for SMA compound library.

GET /api/v2/admet/summary             — overall statistics (BBB count, Lipinski pass, avg QED)
GET /api/v2/admet/compounds            — filter compounds by ADMET properties
GET /api/v2/admet/top                  — top N compounds by QED, CNS MPO, or TPSA
POST /api/v2/admet/predict            — ML-based ADMET prediction (single SMILES)
POST /api/v2/admet/predict/batch      — ML-based ADMET prediction (batch, up to 100 SMILES)
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Literal

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

router = APIRouter()

# Load ADMET results from JSON (generated by compute_admet.py)
_DATA_FILE = Path(__file__).resolve().parents[4] / "data" / "admet_predictions.json"
_admet_data: dict | None = None


def _load_admet() -> dict:
    """Lazy-load ADMET predictions from disk."""
    global _admet_data
    if _admet_data is None:
        if not _DATA_FILE.exists():
            alt = Path("/var/www/sma-research.info/data/admet_predictions.json")
            if alt.exists():
                _admet_data = json.loads(alt.read_text())
            else:
                # Also check the home-based deploy path
                alt2 = Path("/home/bryzant/sma-platform/data/admet_predictions.json")
                if alt2.exists():
                    _admet_data = json.loads(alt2.read_text())
                else:
                    _admet_data = {"summary": {}, "molecules": []}
        else:
            _admet_data = json.loads(_DATA_FILE.read_text())
    return _admet_data


def _molecule_view(mol: dict) -> dict:
    """Build a compact molecule view for API responses."""
    admet = mol.get("admet", {})
    return {
        "id": mol.get("id", ""),
        "target_symbol": mol.get("target_symbol", ""),
        "chembl_id": mol.get("chembl_id", ""),
        "compound_name": mol.get("compound_name", ""),
        "smiles": mol.get("smiles", ""),
        "pchembl_value": mol.get("pchembl_value"),
        "mw": admet.get("mw", 0),
        "logp": admet.get("logp", 0),
        "hbd": admet.get("hbd", 0),
        "hba": admet.get("hba", 0),
        "tpsa": admet.get("tpsa", 0),
        "qed": round(admet.get("qed", 0), 3),
        "rotatable_bonds": admet.get("rotatable_bonds", 0),
        "aromatic_rings": admet.get("aromatic_rings", 0),
        "lipinski_violations": admet.get("lipinski_violations", 0),
        "lipinski_pass": admet.get("lipinski_pass", False),
        "bbb_permeable": admet.get("bbb_permeable", False),
        "cns_mpo": round(admet.get("cns_mpo", 0), 2),
    }


@router.get("/admet/summary")
async def admet_summary():
    """Overall ADMET statistics for the full compound library."""
    data = _load_admet()
    summary = data.get("summary", {})

    # Compute target distribution from molecules
    molecules = data.get("molecules", [])
    target_counts: dict[str, int] = {}
    for mol in molecules:
        sym = mol.get("target_symbol", "unknown")
        target_counts[sym] = target_counts.get(sym, 0) + 1

    # Sort targets by count descending
    top_targets = sorted(target_counts.items(), key=lambda x: x[1], reverse=True)[:20]

    return {
        "total_molecules": summary.get("total_molecules", len(molecules)),
        "computed": summary.get("computed", len(molecules)),
        "bbb_permeable": summary.get("bbb_permeable", 0),
        "lipinski_pass": summary.get("lipinski_pass", 0),
        "high_qed": summary.get("high_qed", 0),
        "cns_mpo_ready": summary.get("cns_mpo_ready", 0),
        "avg_qed": summary.get("avg_qed", 0),
        "avg_cns_mpo": summary.get("avg_cns_mpo", 0),
        "computation_date": data.get("computation_date", ""),
        "target_distribution": [{"symbol": s, "count": c} for s, c in top_targets],
        "bbb_percent": round(100 * summary.get("bbb_permeable", 0) / max(summary.get("total_molecules", 1), 1), 1),
        "lipinski_percent": round(100 * summary.get("lipinski_pass", 0) / max(summary.get("total_molecules", 1), 1), 1),
    }


@router.get("/admet/compounds")
async def admet_compounds(
    bbb: bool | None = Query(default=None, description="Filter by BBB permeability"),
    lipinski: bool | None = Query(default=None, description="Filter by Lipinski compliance"),
    qed_min: float | None = Query(default=None, ge=0, le=1, description="Minimum QED score"),
    qed_max: float | None = Query(default=None, ge=0, le=1, description="Maximum QED score"),
    cns_mpo_min: float | None = Query(default=None, ge=0, le=6, description="Minimum CNS MPO score"),
    mw_max: float | None = Query(default=None, description="Maximum molecular weight"),
    tpsa_max: float | None = Query(default=None, description="Maximum TPSA"),
    target: str | None = Query(default=None, description="Filter by target symbol"),
    limit: int = Query(default=50, ge=1, le=500),
    offset: int = Query(default=0, ge=0),
):
    """Filter compounds by ADMET properties."""
    data = _load_admet()
    molecules = data.get("molecules", [])

    results = []
    for mol in molecules:
        admet = mol.get("admet", {})

        if bbb is not None and admet.get("bbb_permeable", False) != bbb:
            continue
        if lipinski is not None and admet.get("lipinski_pass", False) != lipinski:
            continue
        if qed_min is not None and admet.get("qed", 0) < qed_min:
            continue
        if qed_max is not None and admet.get("qed", 0) > qed_max:
            continue
        if cns_mpo_min is not None and admet.get("cns_mpo", 0) < cns_mpo_min:
            continue
        if mw_max is not None and admet.get("mw", 0) > mw_max:
            continue
        if tpsa_max is not None and admet.get("tpsa", 0) > tpsa_max:
            continue
        if target is not None and mol.get("target_symbol", "").upper() != target.upper():
            continue

        results.append(_molecule_view(mol))

    total = len(results)
    return {
        "total": total,
        "offset": offset,
        "limit": limit,
        "items": results[offset:offset + limit],
    }


@router.get("/admet/top")
async def admet_top(
    n: int = Query(default=20, ge=1, le=200, description="Number of top compounds"),
    sort: Literal["qed", "cns_mpo", "tpsa", "logp", "mw"] = Query(
        default="qed", description="Sort field"
    ),
    bbb: bool | None = Query(default=None, description="Pre-filter by BBB permeability"),
    target: str | None = Query(default=None, description="Filter by target symbol"),
):
    """Top N compounds sorted by a chosen ADMET property."""
    data = _load_admet()
    molecules = data.get("molecules", [])

    filtered = []
    for mol in molecules:
        admet = mol.get("admet", {})
        if bbb is not None and admet.get("bbb_permeable", False) != bbb:
            continue
        if target is not None and mol.get("target_symbol", "").upper() != target.upper():
            continue
        filtered.append(mol)

    # Sort — QED and CNS MPO are "higher is better"; TPSA is "lower is better" for CNS drugs
    reverse = sort in ("qed", "cns_mpo")
    filtered.sort(
        key=lambda m: m.get("admet", {}).get(sort, 0),
        reverse=reverse,
    )

    top = [_molecule_view(m) for m in filtered[:n]]

    return {
        "sort_by": sort,
        "sort_order": "desc" if reverse else "asc",
        "total_pool": len(filtered),
        "returned": len(top),
        "items": top,
    }


# --- ML-based ADMET prediction endpoints (ADMET-AI) ---


class _SmilesInput(BaseModel):
    smiles: str


class _SmilesBatchInput(BaseModel):
    smiles: list[str]


@router.post("/admet/predict")
async def admet_predict_ml(body: _SmilesInput):
    """Predict ADMET properties for a single compound using ML models (ADMET-AI).

    Returns 41 ADMET endpoints from Therapeutics Data Commons benchmarks,
    organized by category (absorption, distribution, metabolism, excretion, toxicity).

    This complements the rule-based predictions in /admet/summary with
    deep learning models trained on experimental data.
    """
    from ...reasoning.admet_ml import (
        predict_admet_ml,
        categorize_predictions,
        compute_druglikeness_summary,
    )

    preds = predict_admet_ml(body.smiles)
    if preds is None:
        raise HTTPException(
            status_code=422,
            detail="ADMET-AI not available or invalid SMILES. Install: pip install admet-ai",
        )

    categorized = categorize_predictions(preds)
    summary = compute_druglikeness_summary(preds)

    return {
        "smiles": body.smiles,
        "method": "ADMET-AI (Chemprop-RDKit, TDC benchmarks)",
        "num_properties": len(preds),
        "overall": summary,
        "categories": categorized,
        "raw_predictions": preds,
    }


@router.post("/admet/predict/batch")
async def admet_predict_ml_batch(body: _SmilesBatchInput):
    """Predict ADMET properties for up to 100 compounds using ML models.

    Returns a list of ADMET predictions, one per input SMILES.
    """
    if len(body.smiles) > 100:
        raise HTTPException(
            status_code=400,
            detail="Maximum 100 SMILES per batch request",
        )

    from ...reasoning.admet_ml import (
        predict_admet_ml_batch,
        compute_druglikeness_summary,
    )

    results = predict_admet_ml_batch(body.smiles)
    if not results:
        raise HTTPException(
            status_code=422,
            detail="ADMET-AI not available or all SMILES invalid. Install: pip install admet-ai",
        )

    # Add summary for each compound
    enriched = []
    for entry in results:
        summary = compute_druglikeness_summary(entry)
        enriched.append({
            "smiles": entry.get("smiles", ""),
            "overall": summary,
            "predictions": {k: v for k, v in entry.items() if k != "smiles"},
        })

    return {
        "method": "ADMET-AI (Chemprop-RDKit, TDC benchmarks)",
        "total": len(enriched),
        "results": enriched,
    }
