"""Pocket druggability endpoints — P2Rank predictions for SMA target structures.

GET /api/v2/pockets            — all pocket predictions
GET /api/v2/pockets/stats      — summary statistics
GET /api/v2/pockets/druggable  — only highly druggable proteins (score>50, prob>0.8)
GET /api/v2/pockets/{symbol}   — pockets for a specific target
"""

from __future__ import annotations

import json
from pathlib import Path

from fastapi import APIRouter, HTTPException, Query

router = APIRouter()

# Load pocket results from JSON (generated by P2Rank)
_DATA_FILE = Path(__file__).resolve().parents[4] / "data" / "pocket_results.json"
_pocket_data: dict | None = None


def _load_pockets() -> dict:
    """Lazy-load pocket results from disk."""
    global _pocket_data
    if _pocket_data is None:
        if not _DATA_FILE.exists():
            alt = Path("/var/www/sma-research.info/data/pocket_results.json")
            if alt.exists():
                _pocket_data = json.loads(alt.read_text())
            else:
                _pocket_data = {}
        else:
            _pocket_data = json.loads(_DATA_FILE.read_text())
    return _pocket_data


def _druggability_label(prob: float) -> str:
    if prob >= 0.8:
        return "Highly Druggable"
    if prob >= 0.5:
        return "Druggable"
    if prob >= 0.2:
        return "Marginal"
    return "Undruggable"


def _build_summary(key: str, entry: dict) -> dict:
    """Build a pocket summary dict for a single structure entry."""
    top_score = entry.get("top_score", 0)
    top_prob = entry.get("top_probability", 0)
    pockets = entry.get("pockets", [])
    return {
        "key": key,
        "symbol": entry.get("symbol", key.split("_")[0]),
        "pdb_file": entry.get("pdb_file", ""),
        "pocket_count": entry.get("pocket_count", 0),
        "top_score": round(top_score, 2),
        "top_probability": round(top_prob, 3),
        "druggable": top_score > 50 and top_prob > 0.8,
        "druggability": _druggability_label(top_prob),
        "top_pocket_residues": pockets[0]["residues"] if pockets else "",
        "top_pocket_residue_count": pockets[0]["residue_count"] if pockets else 0,
    }


@router.get("/pockets")
async def list_pockets(
    min_score: float | None = Query(default=None, description="Minimum top pocket score"),
    min_probability: float | None = Query(default=None, description="Minimum top pocket probability"),
    limit: int = Query(default=100, ge=1, le=500),
    offset: int = Query(default=0, ge=0),
):
    """Return pocket predictions for all structures, sorted by top score descending."""
    data = _load_pockets()
    results = []
    for key, entry in data.items():
        top_score = entry.get("top_score", 0)
        top_prob = entry.get("top_probability", 0)
        if min_score is not None and top_score < min_score:
            continue
        if min_probability is not None and top_prob < min_probability:
            continue
        results.append(_build_summary(key, entry))
    results.sort(key=lambda x: x["top_score"], reverse=True)
    total = len(results)
    return {
        "total": total,
        "offset": offset,
        "limit": limit,
        "items": results[offset:offset + limit],
    }


@router.get("/pockets/stats")
async def pockets_stats():
    """Summary statistics for pocket predictions."""
    data = _load_pockets()
    total_structures = len(data)
    total_pockets = sum(e.get("pocket_count", 0) for e in data.values())
    with_pockets = sum(1 for e in data.values() if e.get("pocket_count", 0) > 0)
    highly_druggable = sum(1 for e in data.values() if e.get("top_probability", 0) >= 0.8)
    druggable = sum(1 for e in data.values() if 0.5 <= e.get("top_probability", 0) < 0.8)
    marginal = sum(1 for e in data.values() if 0.2 <= e.get("top_probability", 0) < 0.5)
    undruggable = sum(1 for e in data.values() if e.get("top_probability", 0) < 0.2)

    scores = [e.get("top_score", 0) for e in data.values() if e.get("pocket_count", 0) > 0]
    avg_score = round(sum(scores) / len(scores), 2) if scores else 0
    max_score = round(max(scores), 2) if scores else 0

    return {
        "total_structures": total_structures,
        "structures_with_pockets": with_pockets,
        "structures_without_pockets": total_structures - with_pockets,
        "total_pockets": total_pockets,
        "avg_pockets_per_structure": round(total_pockets / total_structures, 1) if total_structures else 0,
        "avg_top_score": avg_score,
        "max_top_score": max_score,
        "druggability_distribution": {
            "highly_druggable": highly_druggable,
            "druggable": druggable,
            "marginal": marginal,
            "undruggable": undruggable,
        },
        "method": "P2Rank 2.5.1 (alphafold config)",
        "analysis_date": "2026-03-23",
    }


@router.get("/pockets/druggable")
async def list_druggable_pockets(
    limit: int = Query(default=100, ge=1, le=500),
    offset: int = Query(default=0, ge=0),
):
    """Return only highly druggable proteins (top_score > 50 AND top_probability > 0.8)."""
    data = _load_pockets()
    results = []
    for key, entry in data.items():
        top_score = entry.get("top_score", 0)
        top_prob = entry.get("top_probability", 0)
        if top_score > 50 and top_prob > 0.8:
            summary = _build_summary(key, entry)
            # Include full pocket details for druggable targets
            summary["pockets"] = [
                {
                    "rank": p["rank"],
                    "score": round(p["score"], 2),
                    "probability": round(p["probability"], 3),
                    "center": [round(c, 2) for c in p["center"]],
                    "residues": p["residues"],
                    "residue_count": p["residue_count"],
                    "sas_points": p.get("sas_points", 0),
                    "surf_atoms": p.get("surf_atoms", 0),
                }
                for p in entry.get("pockets", [])
            ]
            results.append(summary)
    results.sort(key=lambda x: x["top_score"], reverse=True)
    total = len(results)
    return {
        "total": total,
        "offset": offset,
        "limit": limit,
        "items": results[offset:offset + limit],
    }


@router.get("/pockets/{symbol}")
async def get_pockets_for_symbol(symbol: str):
    """Return all pocket predictions for a specific target symbol."""
    data = _load_pockets()
    symbol_upper = symbol.upper()

    matches = []
    for key, entry in data.items():
        entry_symbol = entry.get("symbol", key.split("_")[0])
        if entry_symbol.upper() == symbol_upper or key.upper().startswith(symbol_upper + "_"):
            matches.append({
                "key": key,
                "pdb_file": entry.get("pdb_file", ""),
                "pocket_count": entry.get("pocket_count", 0),
                "top_score": round(entry.get("top_score", 0), 2),
                "top_probability": round(entry.get("top_probability", 0), 3),
                "druggable": entry.get("top_score", 0) > 50 and entry.get("top_probability", 0) > 0.8,
                "druggability": _druggability_label(entry.get("top_probability", 0)),
                "pockets": [
                    {
                        "rank": p["rank"],
                        "score": round(p["score"], 2),
                        "probability": round(p["probability"], 3),
                        "center": [round(c, 2) for c in p["center"]],
                        "residues": p["residues"],
                        "residue_count": p["residue_count"],
                        "sas_points": p.get("sas_points", 0),
                        "surf_atoms": p.get("surf_atoms", 0),
                    }
                    for p in entry.get("pockets", [])
                ],
            })

    if not matches:
        raise HTTPException(status_code=404, detail=f"No pocket data for symbol '{symbol}'")

    return {
        "symbol": symbol_upper,
        "structures": matches,
    }
