"""IDH1-mutant intrahepatic Cholangiocarcinoma disease configuration."""

CONFIG = {
    "id": "idh1_icca",
    "name": "IDH1-Mutant Cholangiocarcinoma",
    "short_name": "IDH1-iCCA",
    "description": "Open research platform for IDH1-mutant intrahepatic cholangiocarcinoma",
    "accent_color": "#e67e22",

    "pubmed_queries": [
        "IDH1 cholangiocarcinoma",
        "IDH1 R132C cancer",
        "IDH1 R132H biliary",
        "ivosidenib cholangiocarcinoma",
        "intrahepatic cholangiocarcinoma targeted therapy",
        "IDH1 mutation cancer treatment",
        "cholangiocarcinoma immunotherapy",
        "IDH mutation glioma biliary",
        "2-hydroxyglutarate oncometabolite",
        "IDH inhibitor resistance",
        "cholangiocarcinoma drug resistance",
        "biliary tract cancer molecular",
    ],

    "trial_queries": [
        "IDH1 cholangiocarcinoma",
        "ivosidenib biliary",
        "cholangiocarcinoma targeted therapy",
        "IDH inhibitor cancer",
        "biliary tract cancer immunotherapy",
    ],

    "targets": [
        {"symbol": "IDH1", "name": "Isocitrate Dehydrogenase 1", "target_type": "gene",
         "identifiers": {"uniprot": "O75874", "hgnc": "HGNC:5382", "ensembl": "ENSG00000138413"},
         "description": "Key oncogene in CCA. R132 hotspot mutations produce 2-HG oncometabolite. FDA-approved inhibitor ivosidenib."},
        {"symbol": "IDH2", "name": "Isocitrate Dehydrogenase 2", "target_type": "gene",
         "identifiers": {"uniprot": "P48735", "hgnc": "HGNC:5383", "ensembl": "ENSG00000182054"},
         "description": "Mitochondrial IDH. R140Q/R172K mutations in AML/CCA. Enasidenib approved for AML. Escape route from IDH1 inhibition."},
        {"symbol": "FGFR2", "name": "Fibroblast Growth Factor Receptor 2", "target_type": "gene",
         "identifiers": {"uniprot": "P21802", "hgnc": "HGNC:3689", "ensembl": "ENSG00000066468"},
         "description": "FGFR2 fusions in ~15% iCCA. Pemigatinib/futibatinib approved. Not applicable if no fusion."},
        {"symbol": "BRAF", "name": "B-Raf Proto-Oncogene", "target_type": "gene",
         "identifiers": {"uniprot": "P15056", "hgnc": "HGNC:1097", "ensembl": "ENSG00000157764"},
         "description": "V600E mutation in ~5% CCA. Dabrafenib+trametinib approved for BRAF V600E solid tumors."},
        {"symbol": "KRAS", "name": "KRAS Proto-Oncogene", "target_type": "gene",
         "identifiers": {"uniprot": "P01116", "hgnc": "HGNC:6407", "ensembl": "ENSG00000133703"},
         "description": "Mutated in ~15% iCCA. Currently undruggable except G12C (rare in CCA)."},
        {"symbol": "TP53", "name": "Tumor Protein P53", "target_type": "gene",
         "identifiers": {"uniprot": "P04637", "hgnc": "HGNC:11998", "ensembl": "ENSG00000141510"},
         "description": "Tumor suppressor mutated in ~20% CCA. Loss associated with worse prognosis."},
        {"symbol": "ARID1A", "name": "AT-Rich Interaction Domain 1A", "target_type": "gene",
         "identifiers": {"uniprot": "O14497", "hgnc": "HGNC:11110", "ensembl": "ENSG00000117713"},
         "description": "Chromatin remodeling. Mutated in ~15% iCCA. Loss may sensitize to EZH2/PARP inhibitors."},
        {"symbol": "BAP1", "name": "BRCA1-Associated Protein 1", "target_type": "gene",
         "identifiers": {"uniprot": "Q92560", "hgnc": "HGNC:950", "ensembl": "ENSG00000163930"},
         "description": "Tumor suppressor, deubiquitinase. Mutated in ~15% iCCA. Potential immunotherapy sensitizer."},
        {"symbol": "PBRM1", "name": "Polybromo 1", "target_type": "gene",
         "identifiers": {"uniprot": "Q86U86", "hgnc": "HGNC:30064", "ensembl": "ENSG00000163939"},
         "description": "Chromatin remodeling (SWI/SNF). Mutated in ~10% iCCA. May predict immunotherapy response."},
        {"symbol": "CDKN2A", "name": "Cyclin Dependent Kinase Inhibitor 2A", "target_type": "gene",
         "identifiers": {"uniprot": "P42771", "hgnc": "HGNC:1787", "ensembl": "ENSG00000147889"},
         "description": "Cell cycle regulator (p16). Deleted in ~10% CCA. CDK4/6 inhibitor target."},
        {"symbol": "ERBB2", "name": "Erb-B2 Receptor Tyrosine Kinase 2 (HER2)", "target_type": "gene",
         "identifiers": {"uniprot": "P04626", "hgnc": "HGNC:3430", "ensembl": "ENSG00000141736"},
         "description": "Amplified in ~5% CCA. Trastuzumab deruxtecan showing activity in HER2+ biliary."},
        {"symbol": "PIK3CA", "name": "PI3K Catalytic Subunit Alpha", "target_type": "gene",
         "identifiers": {"uniprot": "P42336", "hgnc": "HGNC:8975", "ensembl": "ENSG00000121879"},
         "description": "PI3K/AKT/mTOR pathway. Mutated in ~5% CCA. Alpelisib potential."},
        {"symbol": "NRAS", "name": "NRAS Proto-Oncogene", "target_type": "gene",
         "identifiers": {"uniprot": "P01111", "hgnc": "HGNC:7989", "ensembl": "ENSG00000213281"},
         "description": "RAS pathway. Rare in CCA (<5%). MEK inhibitor sensitivity."},
        {"symbol": "BRCA1", "name": "BRCA1 DNA Repair", "target_type": "gene",
         "identifiers": {"uniprot": "P38398", "hgnc": "HGNC:1100", "ensembl": "ENSG00000012048"},
         "description": "Homologous recombination repair. Rare in CCA. PARP inhibitor target if mutated."},
        {"symbol": "BRCA2", "name": "BRCA2 DNA Repair", "target_type": "gene",
         "identifiers": {"uniprot": "P51587", "hgnc": "HGNC:1101", "ensembl": "ENSG00000139618"},
         "description": "Homologous recombination repair. Rare in CCA. PARP inhibitor target if mutated."},
    ],

    "drugs": [
        {"name": "Ivosidenib", "status": "approved", "target": "IDH1", "note": "FDA/EMA-approved for IDH1-mutant CCA. Oral, 500mg daily. ClarIDHy trial: mPFS 2.7 vs 1.4mo."},
        {"name": "Enasidenib", "status": "approved", "target": "IDH2", "note": "FDA-approved for IDH2-mutant AML. Potential for IDH2-escape in CCA."},
        {"name": "LY3410738", "status": "phase1", "target": "IDH1/IDH2", "note": "Eli Lilly covalent dual IDH1/2 inhibitor. Overcomes D279N resistance. ORR 42.1%."},
        {"name": "IDH305", "status": "phase1", "target": "IDH1", "note": "Novartis brain-penetrant IDH1 inhibitor."},
        {"name": "Gemcitabine", "status": "approved", "target": "DNA", "note": "Standard 1st-line chemo for CCA (with cisplatin)."},
        {"name": "Cisplatin", "status": "approved", "target": "DNA", "note": "Standard 1st-line chemo for CCA (with gemcitabine)."},
        {"name": "Durvalumab", "status": "approved", "target": "PD-L1", "note": "TOPAZ-1: added to GemCis improves OS in biliary cancer."},
        {"name": "Pemigatinib", "status": "approved", "target": "FGFR2", "note": "For FGFR2 fusion/rearrangement iCCA only."},
        {"name": "Futibatinib", "status": "approved", "target": "FGFR2", "note": "For FGFR2 fusion/rearrangement iCCA only."},
        {"name": "Dabrafenib", "status": "approved", "target": "BRAF", "note": "For BRAF V600E (with trametinib). Tumor-agnostic approval."},
        {"name": "Trametinib", "status": "approved", "target": "MEK", "note": "For BRAF V600E (with dabrafenib). Tumor-agnostic approval."},
        {"name": "Trastuzumab Deruxtecan", "status": "approved", "target": "HER2", "note": "For HER2+ solid tumors. HERB trial in biliary cancer."},
        {"name": "FOLFOX", "status": "approved", "target": "DNA", "note": "2nd-line chemo for CCA. ABC-06 trial."},
        {"name": "Vorasidenib", "status": "phase3", "target": "IDH1/IDH2", "note": "Dual IDH1/2 inhibitor. Approved for glioma, investigating in CCA."},
    ],

    "alias_patterns": {
        "IDH1": ["IDH1", "isocitrate dehydrogenase 1", "R132C", "R132H", "R132G", "R132L", "R132S", "IDH1-mutant", "mIDH1", "IDH1 mutation"],
        "IDH2": ["IDH2", "isocitrate dehydrogenase 2", "R140Q", "R172K", "IDH2-mutant", "mIDH2"],
        "2-HG": ["2-hydroxyglutarate", "2HG", "D-2-HG", "oncometabolite", "alpha-ketoglutarate"],
        "FGFR2": ["FGFR2", "fibroblast growth factor receptor 2", "FGFR2 fusion", "FGFR2-BICC1", "FGFR2 rearrangement"],
        "BRAF": ["BRAF", "B-Raf", "V600E", "BRAF mutation"],
        "KRAS": ["KRAS", "K-Ras", "G12C", "G12D", "G12V"],
        "TP53": ["TP53", "p53", "tumor protein p53"],
        "ARID1A": ["ARID1A", "BAF250a", "SWI/SNF"],
        "BAP1": ["BAP1", "BRCA1-associated protein"],
        "Ivosidenib": ["ivosidenib", "Tibsovo", "AG-120", "ClarIDHy"],
        "Durvalumab": ["durvalumab", "Imfinzi", "TOPAZ-1"],
    },
}
