"""SMA (Spinal Muscular Atrophy) disease configuration."""

CONFIG = {
    "id": "sma",
    "name": "Spinal Muscular Atrophy",
    "short_name": "SMA",
    "description": "Open research platform for Spinal Muscular Atrophy — biology-first target discovery",
    "accent_color": "#4361ee",

    "pubmed_queries": [
        "spinal muscular atrophy",
        "SMN1 SMN2 splicing",
        "SMA motor neuron",
        "nusinersen risdiplam onasemnogene",
        "SMA modifier gene",
        "SMN protein function",
    ],

    "trial_queries": [
        "spinal muscular atrophy",
        "SMA treatment",
        "SMN2 splicing modifier",
    ],

    "targets": [
        {
            "symbol": "SMN1",
            "name": "Survival Motor Neuron 1",
            "target_type": "gene",
            "identifiers": {"hgnc": "HGNC:11117", "ensembl": "ENSG00000172062", "uniprot": "Q16637"},
            "description": "Primary SMA gene. Homozygous deletion/mutation causes SMA. Located on chromosome 5q13.",
        },
        {
            "symbol": "SMN2",
            "name": "Survival Motor Neuron 2",
            "target_type": "gene",
            "identifiers": {"hgnc": "HGNC:11118", "ensembl": "ENSG00000205571", "uniprot": "Q16637"},
            "description": "Paralog of SMN1. Copy number is the primary modifier of SMA severity. C-to-T change in exon 7 causes ~90% exon skipping.",
        },
        {
            "symbol": "STMN2",
            "name": "Stathmin-2 (SCG10)",
            "target_type": "gene",
            "identifiers": {"hgnc": "HGNC:11125", "ensembl": "ENSG00000104435", "uniprot": "Q93045"},
            "description": "Microtubule regulator critical for axonal growth. Downregulated in SMA motor neurons. Top neuroprotective target.",
        },
        {
            "symbol": "PLS3",
            "name": "Plastin 3 (T-plastin)",
            "target_type": "gene",
            "identifiers": {"hgnc": "HGNC:9090", "ensembl": "ENSG00000214765", "uniprot": "P13797"},
            "description": "Actin-bundling protein. Natural modifier of SMA severity in discordant families.",
        },
        {
            "symbol": "NCALD",
            "name": "Neurocalcin Delta",
            "target_type": "gene",
            "identifiers": {"hgnc": "HGNC:7654", "ensembl": "ENSG00000104490", "uniprot": "P61601"},
            "description": "Calcium sensor. Reduced NCALD expression rescues SMA phenotype in animal models.",
        },
        {
            "symbol": "UBA1",
            "name": "Ubiquitin-Like Modifier Activating Enzyme 1",
            "target_type": "gene",
            "identifiers": {"hgnc": "HGNC:12469", "ensembl": "ENSG00000130985", "uniprot": "P22314"},
            "description": "Ubiquitin-activating enzyme. Dysregulated in SMA, linked to ubiquitin homeostasis defects.",
        },
        {
            "symbol": "CORO1C",
            "name": "Coronin 1C",
            "target_type": "gene",
            "identifiers": {"hgnc": "HGNC:2254"},
            "description": "Actin-binding protein. Potential SMA modifier through interactome studies.",
        },
        {
            "symbol": "SMN_PROTEIN",
            "name": "SMN Protein Complex",
            "target_type": "protein",
            "identifiers": {"uniprot": "Q16637"},
            "description": "Essential for snRNP biogenesis and pre-mRNA splicing. Loss of full-length SMN protein causes SMA.",
        },
        {
            "symbol": "MTOR_PATHWAY",
            "name": "mTOR Signaling Pathway",
            "target_type": "pathway",
            "identifiers": {"reactome": "R-HSA-165159", "kegg": "hsa04150"},
            "description": "Dysregulated in SMA motor neurons. mTOR hyperactivation may contribute to neurodegeneration.",
        },
        {
            "symbol": "NMJ_MATURATION",
            "name": "Neuromuscular Junction Maturation",
            "target_type": "pathway",
            "identifiers": {},
            "description": "NMJ defects are among the earliest pathological features of SMA.",
        },
    ],

    "drugs": [
        {
            "name": "nusinersen",
            "brand_names": ["Spinraza"],
            "drug_type": "aso",
            "mechanism": "Antisense oligonucleotide targeting SMN2 pre-mRNA ISS-N1 to promote exon 7 inclusion.",
            "approval_status": "approved",
            "approved_for": ["type1", "type2", "type3", "presymptomatic"],
            "manufacturer": "Biogen",
            "status": "approved",
            "target": "SMN2",
        },
        {
            "name": "risdiplam",
            "brand_names": ["Evrysdi"],
            "drug_type": "splice_modifier",
            "mechanism": "Small molecule SMN2 splicing modifier. Promotes exon 7 inclusion. Oral, crosses BBB.",
            "approval_status": "approved",
            "approved_for": ["type1", "type2", "type3"],
            "manufacturer": "Roche/Genentech",
            "status": "approved",
            "target": "SMN2",
        },
        {
            "name": "onasemnogene abeparvovec",
            "brand_names": ["Zolgensma"],
            "drug_type": "gene_therapy",
            "mechanism": "AAV9-mediated gene replacement delivering functional SMN1. Single IV infusion.",
            "approval_status": "approved",
            "approved_for": ["type1", "presymptomatic"],
            "manufacturer": "Novartis Gene Therapies",
            "status": "approved",
            "target": "SMN1",
        },
        {
            "name": "apitegromab",
            "brand_names": [],
            "drug_type": "antibody",
            "mechanism": "Anti-myostatin antibody (SRK-015). Inhibits latent myostatin activation.",
            "approval_status": "phase3",
            "approved_for": [],
            "manufacturer": "Scholar Rock",
            "status": "phase3",
            "target": "myostatin",
        },
        {
            "name": "taldefgrobep alfa",
            "brand_names": ["GYM329"],
            "drug_type": "antibody",
            "mechanism": "Anti-latent myostatin antibody. Muscle-enhancing adjunct to SMN-restoring therapies.",
            "approval_status": "phase3",
            "approved_for": [],
            "manufacturer": "Roche",
            "status": "phase3",
            "target": "myostatin",
        },
        {
            "name": "reldesemtiv",
            "brand_names": [],
            "drug_type": "small_molecule",
            "mechanism": "Fast skeletal muscle troponin activator. Enhances muscle force production.",
            "approval_status": "phase2",
            "approved_for": [],
            "manufacturer": "Cytokinetics",
            "status": "phase2",
            "target": "troponin",
        },
        {
            "name": "pyridostigmine",
            "brand_names": ["Mestinon"],
            "drug_type": "small_molecule",
            "mechanism": "Acetylcholinesterase inhibitor. Improves neuromuscular transmission at the NMJ.",
            "approval_status": "phase2",
            "approved_for": [],
            "manufacturer": "Various",
            "status": "phase2",
            "target": "AChE",
        },
    ],

    "alias_patterns": {
        "SMN1": ["SMN1", "survival motor neuron 1"],
        "SMN2": ["SMN2", "survival motor neuron 2"],
        "STMN2": ["STMN2", "stathmin-2", "SCG10"],
        "PLS3": ["PLS3", "plastin 3", "T-plastin"],
        "NCALD": ["NCALD", "neurocalcin delta"],
        "UBA1": ["UBA1", "ubiquitin-activating enzyme 1"],
        "CORO1C": ["CORO1C", "coronin 1C"],
    },
}
