#!/usr/bin/env python3
"""
DiffDock Batch Docking: 107 GenMol ROCK2 Molecules
===================================================
Campaign date: 2026-03-24
Rationale: Dock 107 drug-like molecules generated by GenMol (seeded from
           Fasudil and Y-27632) against ROCK2 kinase domain via DiffDock v2.2 NIM.

Input:  data/docking/genmol_rock2_2026-03-24.json  (107 molecules)
Target: data/structures/ROCK2_O75116_kinase.pdb     (trimmed kinase domain)
Output: data/docking/genmol_rock2_docking_2026-03-24.json

Usage:
    export NVIDIA_API_KEY=...
    python scripts/dock_genmol_rock2_batch.py
"""

import asyncio
import json
import logging
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

# --- Configuration ---
NVIDIA_API_KEY = os.environ.get("NVIDIA_API_KEY", "")
if not NVIDIA_API_KEY:
    raise RuntimeError("NVIDIA_API_KEY environment variable is required")

DIFFDOCK_URL = "https://health.api.nvidia.com/v1/biology/mit/diffdock"
NUM_POSES = 20  # NEVER use 5 — always 20 for validation
RATE_LIMIT_DELAY = 2.0  # seconds between requests

# Resolve paths relative to project root
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
DATA_DIR = PROJECT_ROOT / "data"
STRUCTURES_DIR = DATA_DIR / "structures"
DOCKING_DIR = DATA_DIR / "docking"

INPUT_JSON = DOCKING_DIR / "genmol_rock2_2026-03-24.json"
OUTPUT_JSON = DOCKING_DIR / "genmol_rock2_docking_2026-03-24.json"
PDB_FILE = STRUCTURES_DIR / "ROCK2_O75116_kinase.pdb"


def smiles_to_sdf(smiles: str, name: str = "") -> str:
    """Convert SMILES to SDF format using RDKit.

    DiffDock NIM v2.2 rejects ligand_file_type='smiles' — requires SDF.
    """
    from rdkit import Chem
    from rdkit.Chem import AllChem

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"Invalid SMILES: {smiles}")
    mol = Chem.AddHs(mol)
    result = AllChem.EmbedMolecule(mol, AllChem.ETKDGv3())
    if result == -1:
        AllChem.EmbedMolecule(mol, randomSeed=42)
    AllChem.MMFFOptimizeMolecule(mol)
    if name:
        mol.SetProp("_Name", name)
    return Chem.MolToMolBlock(mol)


async def dock_molecule(
    protein_pdb: str,
    smiles: str,
    mol_index: int,
    mol_info: dict,
) -> dict:
    """Dock a single molecule against ROCK2 using DiffDock NIM."""
    import httpx

    name = f"GenMol_{mol_index:03d}"

    # Convert SMILES to SDF
    try:
        ligand_sdf = smiles_to_sdf(smiles, name=name)
    except Exception as e:
        return {
            "index": mol_index,
            "name": name,
            "smiles": smiles,
            "error": f"SDF conversion failed: {e}",
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

    payload = {
        "ligand": ligand_sdf,
        "ligand_file_type": "sdf",
        "protein": protein_pdb,
        "num_poses": NUM_POSES,
        "time_divisions": 20,
        "steps": 18,
        "save_trajectory": False,
    }

    headers = {
        "Authorization": f"Bearer {NVIDIA_API_KEY}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }

    max_retries = 3
    for attempt in range(max_retries):
        try:
            async with httpx.AsyncClient(timeout=120) as client:
                resp = await client.post(DIFFDOCK_URL, json=payload, headers=headers)

                if resp.status_code == 400:
                    logger.error(f"  400 Bad Request for {name}: {resp.text[:300]}")
                    return {
                        "index": mol_index,
                        "name": name,
                        "smiles": smiles,
                        "error": f"400 Bad Request: {resp.text[:200]}",
                        "timestamp": datetime.now(timezone.utc).isoformat(),
                    }

                if resp.status_code in (429, 503):
                    wait = (attempt + 1) * 10
                    logger.warning(f"  {resp.status_code} for {name}, retry {attempt+1}/{max_retries} in {wait}s...")
                    await asyncio.sleep(wait)
                    continue

                resp.raise_for_status()
                result = resp.json()
                break
        except httpx.TimeoutException:
            if attempt < max_retries - 1:
                logger.warning(f"  Timeout for {name}, retry {attempt+1}/{max_retries}...")
                await asyncio.sleep(5)
                continue
            return {
                "index": mol_index,
                "name": name,
                "smiles": smiles,
                "error": "Timeout after retries",
                "timestamp": datetime.now(timezone.utc).isoformat(),
            }
        except Exception as e:
            if attempt < max_retries - 1:
                logger.warning(f"  Error for {name}: {e}, retry {attempt+1}/{max_retries}...")
                await asyncio.sleep(5)
                continue
            return {
                "index": mol_index,
                "name": name,
                "smiles": smiles,
                "error": str(e),
                "timestamp": datetime.now(timezone.utc).isoformat(),
            }

    # Parse DiffDock v2.2 response
    confidences = result.get("position_confidence", [])
    if not confidences:
        poses = result.get("output", []) if isinstance(result.get("output"), list) else []
        if not poses:
            poses = result.get("poses", [])
        for pose in poses:
            if isinstance(pose, dict):
                conf = pose.get("confidence", pose.get("score", None))
                if conf is not None:
                    confidences.append(float(conf))
        if not confidences and "confidence" in result:
            confidences = [float(result["confidence"])]

    confidences = [float(c) for c in confidences]
    top_confidence = max(confidences) if confidences else None
    mean_confidence = sum(confidences) / len(confidences) if confidences else None

    return {
        "index": mol_index,
        "name": name,
        "smiles": smiles,
        "seed": mol_info.get("seed", "unknown"),
        "mw": mol_info.get("mw"),
        "logp": mol_info.get("logp"),
        "qed": mol_info.get("qed"),
        "hba": mol_info.get("hba"),
        "hbd": mol_info.get("hbd"),
        "tpsa": mol_info.get("tpsa"),
        "num_poses": len(confidences),
        "num_poses_requested": NUM_POSES,
        "top_confidence": top_confidence,
        "mean_confidence": mean_confidence,
        "all_confidences": sorted(confidences, reverse=True) if confidences else [],
        "positive_poses": len([c for c in confidences if c > 0]),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


async def run_batch():
    """Run batch docking of 107 GenMol molecules against ROCK2."""

    # Load molecules
    with open(INPUT_JSON) as f:
        data = json.load(f)

    molecules = data.get("all_drug_like", [])
    if not molecules:
        molecules = data.get("top_candidates", [])
    logger.info(f"Loaded {len(molecules)} molecules from {INPUT_JSON}")

    # Load ROCK2 kinase PDB (ATOM lines only)
    pdb_text = PDB_FILE.read_text()
    protein_pdb = '\n'.join(l for l in pdb_text.split('\n') if l.startswith('ATOM'))
    atom_count = protein_pdb.count('\n') + 1
    logger.info(f"Loaded ROCK2 kinase PDB: {atom_count} ATOM lines")

    # Check for existing partial results (resume support)
    completed_smiles = set()
    existing_results = []
    if OUTPUT_JSON.exists():
        try:
            with open(OUTPUT_JSON) as f:
                existing_data = json.load(f)
            existing_results = existing_data.get("results", [])
            completed_smiles = {r["smiles"] for r in existing_results if r.get("top_confidence") is not None}
            if completed_smiles:
                logger.info(f"Resuming: {len(completed_smiles)} molecules already docked, skipping them")
        except Exception:
            pass

    # Run dockings
    results = list(existing_results)
    remaining = [(i, m) for i, m in enumerate(molecules) if m["smiles"] not in completed_smiles]
    total = len(molecules)
    done = len(completed_smiles)

    logger.info("=" * 70)
    logger.info(f"GenMol ROCK2 Batch Docking — {len(remaining)} remaining of {total}")
    logger.info(f"Target: ROCK2 kinase domain (O75116, residues 18-413)")
    logger.info(f"Poses: {NUM_POSES} per molecule")
    logger.info(f"Rate limit: {RATE_LIMIT_DELAY}s between requests")
    est_minutes = len(remaining) * (RATE_LIMIT_DELAY + 8) / 60  # ~8s per dock + 2s delay
    logger.info(f"Estimated time: ~{est_minutes:.0f} minutes")
    logger.info("=" * 70)

    for idx, (mol_idx, mol) in enumerate(remaining):
        done += 1
        smiles = mol["smiles"]
        seed = mol.get("seed", "?")
        qed = mol.get("qed", 0)
        logger.info(f"\n[{done}/{total}] Docking GenMol_{mol_idx:03d} (seed={seed}, QED={qed:.3f})...")
        logger.info(f"  SMILES: {smiles}")

        result = await dock_molecule(protein_pdb, smiles, mol_idx, mol)
        results.append(result)

        conf = result.get("top_confidence")
        if conf is not None:
            label = "BINDING" if conf > 0 else "no binding"
            logger.info(f"  -> top_confidence: {conf:.4f} ({label})")
            logger.info(f"  -> positive poses: {result.get('positive_poses', 0)}/{result.get('num_poses', '?')}")
        elif result.get("error"):
            logger.error(f"  -> ERROR: {result['error']}")

        # Save intermediate results every 10 molecules
        if done % 10 == 0 or idx == len(remaining) - 1:
            save_results(data, molecules, results)
            logger.info(f"  [checkpoint saved: {done}/{total}]")

        # Rate limiting
        if idx < len(remaining) - 1:
            await asyncio.sleep(RATE_LIMIT_DELAY)

    # Final save
    save_results(data, molecules, results)
    logger.info(f"\nFinal results saved to {OUTPUT_JSON}")

    # Print summary
    print_summary(results)

    return results


def save_results(input_data: dict, molecules: list, results: list):
    """Save results to JSON with metadata."""
    DOCKING_DIR.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_JSON, "w") as f:
        json.dump({
            "campaign": "GenMol ROCK2 batch docking",
            "date": "2026-03-24",
            "diffdock_version": "v2.2 (NVIDIA NIM)",
            "num_poses": NUM_POSES,
            "target": {
                "symbol": "ROCK2",
                "uniprot": "O75116",
                "domain": "kinase (residues 18-413)",
                "pdb_file": "ROCK2_O75116_kinase.pdb",
            },
            "input": {
                "file": str(INPUT_JSON.name),
                "total_molecules": len(molecules),
                "seeds": list(input_data.get("seeds", {}).keys()),
                "filters": input_data.get("filters", {}),
            },
            "benchmarks": {
                "Y-27632_ROCK2": "+0.46 (best from prior campaign)",
                "Fasudil_ROCK2": "-0.006 (surprisingly weak)",
            },
            "results": results,
            "summary": compute_summary(results),
        }, f, indent=2)


def compute_summary(results: list) -> dict:
    """Compute summary statistics."""
    successful = [r for r in results if r.get("top_confidence") is not None]
    errors = [r for r in results if r.get("error")]
    positive = [r for r in successful if r["top_confidence"] > 0]

    if not successful:
        return {"total": len(results), "successful": 0, "errors": len(errors)}

    confs = [r["top_confidence"] for r in successful]
    return {
        "total": len(results),
        "successful": len(successful),
        "errors": len(errors),
        "positive_binders": len(positive),
        "negative_binders": len(successful) - len(positive),
        "best_confidence": max(confs),
        "worst_confidence": min(confs),
        "mean_confidence": sum(confs) / len(confs),
        "median_confidence": sorted(confs)[len(confs) // 2],
        "beat_y27632": len([c for c in confs if c > 0.46]),
        "beat_fasudil": len([c for c in confs if c > -0.006]),
    }


def print_summary(results: list):
    """Print formatted summary of docking results."""
    successful = [r for r in results if r.get("top_confidence") is not None]
    errors = [r for r in results if r.get("error")]
    positive = [r for r in successful if r["top_confidence"] > 0]

    logger.info("\n" + "=" * 70)
    logger.info("BATCH DOCKING SUMMARY")
    logger.info("=" * 70)
    logger.info(f"Total molecules:     {len(results)}")
    logger.info(f"Successful dockings: {len(successful)}")
    logger.info(f"Errors:              {len(errors)}")
    logger.info(f"Positive binders:    {len(positive)} ({len(positive)/max(len(successful),1)*100:.0f}%)")
    logger.info(f"Negative binders:    {len(successful) - len(positive)}")

    if successful:
        confs = [r["top_confidence"] for r in successful]
        logger.info(f"\nConfidence range: {min(confs):.4f} to {max(confs):.4f}")
        logger.info(f"Mean confidence:  {sum(confs)/len(confs):.4f}")

        # Benchmark comparison
        beat_y27632 = [r for r in successful if r["top_confidence"] > 0.46]
        beat_fasudil = [r for r in successful if r["top_confidence"] > -0.006]
        logger.info(f"\nBeat Y-27632 (+0.46): {len(beat_y27632)}")
        logger.info(f"Beat Fasudil (-0.006): {len(beat_fasudil)}")

        # Top 20 ranked
        logger.info("\n--- TOP 20 by confidence ---")
        for rank, r in enumerate(sorted(successful, key=lambda x: x["top_confidence"], reverse=True)[:20], 1):
            binding = "BIND" if r["top_confidence"] > 0 else "----"
            logger.info(
                f"  {rank:2d}. [{binding}] {r['name']:12s} conf={r['top_confidence']:+.4f}  "
                f"seed={r.get('seed','?'):10s} QED={r.get('qed',0):.3f} "
                f"MW={r.get('mw',0):.0f} "
                f"pos_poses={r.get('positive_poses',0)}/{r.get('num_poses','?')}"
            )
            logger.info(f"       SMILES: {r['smiles']}")

        # Scaffold analysis: group by seed
        logger.info("\n--- By seed ---")
        for seed_name in ["Fasudil", "Y-27632"]:
            seed_results = [r for r in successful if r.get("seed") == seed_name]
            if seed_results:
                seed_confs = [r["top_confidence"] for r in seed_results]
                seed_pos = [r for r in seed_results if r["top_confidence"] > 0]
                best = max(seed_results, key=lambda x: x["top_confidence"])
                logger.info(
                    f"  {seed_name}: {len(seed_results)} molecules, "
                    f"{len(seed_pos)} positive ({len(seed_pos)/len(seed_results)*100:.0f}%), "
                    f"best={best['top_confidence']:+.4f} ({best['name']}), "
                    f"mean={sum(seed_confs)/len(seed_confs):.4f}"
                )

    if errors:
        logger.info(f"\n--- Errors ({len(errors)}) ---")
        for r in errors[:5]:
            logger.info(f"  {r.get('name','?')}: {r['error'][:100]}")
        if len(errors) > 5:
            logger.info(f"  ... and {len(errors)-5} more")


if __name__ == "__main__":
    asyncio.run(run_batch())
